---
- import_tasks: packages.yml
  tags: [packages]

- import_tasks: grafana.yml
  tags: [grafana]

- import_tasks: collectd.yml
  tags: [collectd]

- import_tasks: telegraf.yml
  tags: [telegraf]

- import_tasks: prometheus.yml
  tags: [prometheus]

- import_tasks: nginx.yml
  tags: [nginx]
